### ISSUE TITLE
typo in command

### ISSUE THREAD

**Issue by Dante-666** [abel0b/setup-premake#1]
Hey, this works, I just wanted to let you know that the readme and marketplace has this @ which is confusing to newbs :P

@abel0b/setup-premake@v1
-->
abel0b/setup-premake@v1

**Comment by abel0b** [comment]
Thanks! It's merged

**Comment by Dante-666** [comment]
Thanks for merging it but for some reason in the CI machines, it still doesn't read the C++20 flag. The same binaries from the same source do in my local machine. I'll try this again later :)

**Comment by abel0b** [comment]
Have you specified the right version in action config?
Ive not released a new version number yet.
But Github action allows to select version by commit hash :
```
-  uses: abel0b/setup-premake@8463d9a3b900273c6863825a886aaa3a129f7db6
```

**Comment by Dante-666** [comment]
Now it makes sense why it didn't work. I am new to github actions, thanks a bunch for clarifying this.
It's working now.
